language: node_js
node_js:
- '8'
install: yarn
script: gatsby build
deploy:
  provider: s3
  access_key_id: $AWSKEY
  secret_access_key: $AWSSK
  bucket: "www.securityburst.com"
  skip_cleanup: true
  acl: public_read
  local_dir: public
